"""delete cpf

Revision ID: 5787c8cbbb39
Revises: a5e460c5bc8a
Create Date: 2025-10-03 17:17:49.150191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5787c8cbbb39'
down_revision: Union[str, Sequence[str], None] = 'a5e460c5bc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
