"""create cpf

Revision ID: a5e460c5bc8a
Revises: c567b0742304
Create Date: 2025-10-03 17:16:20.951130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e460c5bc8a'
down_revision: Union[str, Sequence[str], None] = 'c567b0742304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###
